package by.ivam.fellowtravelerbot.bot.enums;

import lombok.Getter;

@Getter
public enum CarOperation {
    ADD_CAR_REQUEST_CALLBACK,
    ADD_CAR_START_CALLBACK,
    ADD_CAR_MODEL_CHAT_STATUS,
    ADD_CAR_COLOR_CHAT_STATUS,
    ADD_CAR_PLATES_CHAT_STATUS,
    ADD_CAR_COMMENTARY_CHAT_STATUS,
    ADD_CAR_SKIP_COMMENT_CALLBACK,
    ADD_CAR_SAVE_CAR_CALLBACK,
    ADD_CAR_EDIT_CAR_CALLBACK,
    EDIT_CAR_REQUEST_CALLBACK,
    DELETE_CAR_REQUEST_CALLBACK

}
