package by.ivam.fellowtravelerbot.bot.enums;

import lombok.Getter;

@Getter
public enum CarOperation {
    ADD_CAR_REQUEST_CALLBACK("ADD_CAR_REQUEST_CALLBACK"),
    ADD_CAR_START_CALLBACK("ADD_CAR_START_CALLBACK"),
    ADD_CAR_MODEL_CHAT_STATUS("ADD_CAR_MODEL_CHAT_STATUS"),
    ADD_CAR_COLOR_CHAT_STATUS("ADD_CAR_COLOR_CHAT_STATUS"),
    ADD_CAR_PLATES_CHAT_STATUS("ADD_CAR_PLATES_CHAT_STATUS"),
    ADD_CAR_COMMENTARY_CHAT_STATUS("ADD_CAR_COMMENTARY_CHAT_STATUS"),
    ADD_CAR_SKIP_COMMENT_CALLBACK("ADD_CAR_SKIP_COMMENT_CALLBACK"),
    ADD_CAR_SAVE_CAR_CALLBACK("ADD_CAR_SAVE_CAR_CALLBACK"),
    ADD_CAR_EDIT_MODEL_CALLBACK("ADD_CAR_EDIT_MODEL_CALLBACK"),
    ADD_CAR_EDIT_MODEL_CHAT_STATUS("ADD_CAR_EDIT_MODEL_CHAT_STATUS"),
    ADD_CAR_EDIT_COLOR_CALLBACK("ADD_CAR_EDIT_COLOR_CALLBACK"),
    ADD_CAR_EDIT_COLOR_CHAT_STATUS("ADD_CAR_EDIT_COLOR_CHAT_STATUS"),
    ADD_CAR_EDIT_PLATES_CALLBACK("ADD_CAR_EDIT_PLATES_CALLBACK"),
    ADD_CAR_EDIT_PLATES_CHAT_STATUS("ADD_CAR_EDIT_PLATES_CHAT_STATUS"),
    ADD_CAR_EDIT_COMMENTARY_CALLBACK("ADD_CAR_EDIT_COMMENTARY_CALLBACK"),
    ADD_CAR_EDIT_COMMENTARY_CHAT_STATUS("ADD_CAR_EDIT_COMMENTARY_CHAT_STATUS"),
    ADD_CAR_EDIT_CAR_CALLBACK("ADD_CAR_EDIT_CAR_CALLBACK"),
    EDIT_CAR_REQUEST_CALLBACK("EDIT_CAR_REQUEST_CALLBACK"),
    EDIT_CAR_CHOOSE_CAR_CALLBACK("EDIT_CAR_CHOOSE_CAR_CALLBACK:"),
    EDIT_CAR_MODEL_CALLBACK("EDIT_CAR_MODEL_CALLBACK:"),
    EDIT_CAR_MODEL_CHAT_STATUS("EDIT_CAR_MODEL_CHAT_STATUS:"),
    EDIT_CAR_COLOR_CALLBACK("EDIT_CAR_COLOR_CALLBACK:"),
    EDIT_CAR_COLOR_CHAT_STATUS("EDIT_CAR_COLOR_CHAT_STATUS:"),
    EDIT_CAR_PLATES_CALLBACK("EDIT_CAR_PLATES_CALLBACK:"),
    EDIT_CAR_PLATES_CHAT_STATUS("EDIT_CAR_PLATES_CHAT_STATUS:"),
    EDIT_CAR_COMMENTARY_CALLBACK("EDIT_FIRST_CAR_EDIT_COMMENTARY_CALLBACK:"),
    EDIT_CAR_COMMENTARY_CHAT_STATUS("EDIT_CAR_COMMENTARY_CHAT_STATUS:"),
//      EDIT_FIRST_CAR_EDIT_MODEL_CALLBACK(""),
//    EDIT_FIRST_CAR_EDIT_COLOR_CALLBACK(""),
//    EDIT_FIRST_CAR_EDIT_PLATES_CALLBACK(""),
//    EDIT_FIRST_CAR_EDIT_COMMENTARY_CALLBACK(""),
//    
    DELETE_CAR_REQUEST_CALLBACK("DELETE_CAR_REQUEST_CALLBACK");
    private final String value;

    CarOperation(String value) {
        this.value = value;
    }
}
