package by.ivam.fellowtravelerbot.bot.enums;

import lombok.Getter;

@Getter
public enum FindPassengerOperation {
    CREATE_FIND_PASSENGER_REQUEST_CALLBACK("CREATE_FIND_PASSENGER_REQUEST_CALLBACK"),
    CREATE_FIND_PASSENGER_REQUEST_DIRECTION_CALLBACK("CREATE_FIND_PAS_REQUEST_DIRECTION:"),
    CREATE_FIND_PASSENGER_REQUEST_SETTLEMENT_CALLBACK("CREATE_REQ_DEP_SETTLEMENT:"),
    CREATE_FIND_PASSENGER_REQUEST_ANOTHER_SETTLEMENT_CALLBACK("CREATE_REQ_ANOTHER_SETTLEMENT"),
    CREATE_REQUEST_DEP_LOCATION_CALLBACK("CREATE_REQUEST_DEP_LOCATION:");

    private final String value;
    FindPassengerOperation(String value) {
        this.value = value;
    }
}
