package by.ivam.fellowtravelerbot.bot.enums;

import lombok.Getter;

@Getter
public enum FindPassengerOperation {
    CREATE_FIND_PASSENGER_REQUEST_CALLBACK("CREATE_FIND_PASSENGER_REQUEST_CALLBACK"),
    CREATE_REQUEST_DIRECTION_CALLBACK("CREATE_REQUEST_DIRECTION:"),
    CREATE_REQUEST_SETTLEMENT_CALLBACK("CREATE_REQ_DEP_SETTLEMENT:"),
    CREATE_REQUEST_ANOTHER_SETTLEMENT_CALLBACK("CREATE_REQ_ANOTHER_SETTLEMENT"),
    CREATE_REQUEST_DEP_LOCATION_CALLBACK("CREATE_REQUEST_DEP_LOCATION:"),
    CREATE_REQUEST_DESTINATION_SETTLEMENT_CALLBACK("CREATE_REQ_DEST_SETTLEMENT:"),
    CREATE_REQUEST_ANOTHER_DESTINATION_SETTLEMENT_CALLBACK("CREATE_REQ_ANOTHER_DEST_SETTLEMENT"),
    CREATE_REQUEST_DESTINATION_LOCATION_CALLBACK("CREATE_REQUEST_DEST_LOCATION:"),
    CREATE_REQUEST_DATE_CALLBACK("CREATE_REQUEST_DATE:"),
    CREATE_REQUEST_TIME_STATUS("CREATE_REQUEST_TIME_STATUS"),
    CREATE_REQUEST_TIME_CALLBACK("CREATE_REQUEST_TIME_CALLBACK:"),
    CREATE_REQUEST_CAR_CALLBACK("CREATE_REQUEST_CAR_CALLBACK:"),
    CREATE_REQUEST_SEATS_STATUS("CREATE_REQUEST_SEATS_STATUS"),
    CREATE_REQUEST_COMMENTARY_STATUS("CREATE_REQUEST_COMMENTARY_STATUS"),
    CREATE_REQUEST_SKIP_COMMENT_CALLBACK("CREATE_REQUEST_SKIP_COMMENT"),
    SAVE_REQUEST_CALLBACK("SAVE_REQUEST_CALLBACK"),
    EDIT_BEFORE_SAVE_REQUEST_CALLBACK("EDIT_BEFORE_SAVE_REQUEST_CALLBACK"),
    ;

    private final String value;
    FindPassengerOperation(String value) {
        this.value = value;
    }
}
