package by.ivam.fellowtravelerbot.bot.enums;

import lombok.Getter;

@Getter
public enum FindPassengerOperation {
    CREATE_FIND_PASSENGER_REQUEST_CALLBACK("CREATE_FIND_PASSENGER_REQUEST_CALLBACK"),
    CREATE_REQUEST_DIRECTION_CALLBACK("CREATE_REQUEST_DIRECTION:"),
    CREATE_REQUEST_SETTLEMENT_CALLBACK("CREATE_REQ_DEP_SETTLEMENT:"),
    CREATE_REQUEST_ANOTHER_SETTLEMENT_CALLBACK("CREATE_REQ_ANOTHER_SETTLEMENT"),
    CREATE_REQUEST_DEP_LOCATION_CALLBACK("CREATE_REQUEST_DEP_LOCATION:"),
    CREATE_REQUEST_DESTINATION_SETTLEMENT_CALLBACK("CREATE_REQ_DEST_SETTLEMENT:"),
    CREATE_REQUEST_ANOTHER_DESTINATION_SETTLEMENT_CALLBACK("CREATE_REQ_ANOTHER_DEST_SETTLEMENT"),
    CREATE_REQUEST_DESTINATION_LOCATION_CALLBACK("CREATE_REQUEST_DEST_LOCATION:"),
    CREATE_REQUEST_DATE_CALLBACK("CREATE_REQUEST_DATE:"),
    CREATE_REQUEST_TIME_STATUS("CREATE_REQUEST_TIME_STATUS"),
    CREATE_REQUEST_TIME_CALLBACK("CREATE_REQUEST_TIME_CALLBACK:"),
    CREATE_REQUEST_CAR_CALLBACK("CREATE_REQUEST_CAR_CALLBACK:"),
    CREATE_REQUEST_SEATS_STATUS("CREATE_REQUEST_SEATS_STATUS"),
    CREATE_REQUEST_COMMENTARY_STATUS("CREATE_REQUEST_COMMENTARY_STATUS"),
    CREATE_REQUEST_SKIP_COMMENT_CALLBACK("CREATE_REQUEST_SKIP_COMMENT"),
    SAVE_REQUEST_CALLBACK("SAVE_REQUEST_CALLBACK"),
    EDIT_BEFORE_SAVE_REQUEST_CALLBACK("EDIT_BEFORE_SAVE_REQUEST_CALLBACK"),
    EDIT_BEFORE_SAVE_SETTLEMENT_LOCATION_CALLBACK("EDIT_BEFORE_SAVE_SETTLEMENT_LOCATION"),
    EDIT_BEFORE_SAVE_DATE_TAME_CALLBACK("EDIT_BEFORE_SAVE_DATE_TAME"),
    EDIT_BEFORE_SAVE_CAR_DETAILS_CALLBACK("EDIT_BEFORE_SAVE_CAR_DETAILS"),
    EDIT_BEFORE_SAVE_DEPARTURE_SETTLEMENT_CALLBACK("EDIT_BEFORE_SAVE_DEP_SETTLEMENT"),
    EDIT_BEFORE_SAVE_CHANGE_DEPARTURE_SETTLEMENT_CALLBACK("EDIT_BEFORE_SAVE_CHANGE_DEP_SETTLEMENT:"),
    EDIT_BEFORE_SAVE_DESTINATION_SETTLEMENT_CALLBACK("EDIT_BEFORE_SAVE_DEST_SETTLEMENT"),
    EDIT_BEFORE_SAVE_CHANGE_DESTINATION_SETTLEMENT_CALLBACK("EDIT_BEFORE_SAVE_CHANGE_DEST_SETTLEMENT:"),
    EDIT_BEFORE_SAVE_DEPARTURE_LOCATION_CALLBACK("EDIT_BEFORE_SAVE_DEP_LOCATION"),
    EDIT_BEFORE_SAVE_CHANGE_DEPARTURE_LOCATION_CALLBACK("EDIT_BEFORE_SAVE_CHANGE_DEP_LOCATION:"),
    EDIT_BEFORE_SAVE_DESTINATION_LOCATION_CALLBACK("EDIT_BEFORE_SAVE_DEST_LOCATION"),
    EDIT_BEFORE_SAVE_CHANGE_DESTINATION_LOCATION_CALLBACK("EDIT_BEFORE_SAVE_CHANGE_DEST_LOCATION:"),
    EDIT_BEFORE_SAVE_SWAP_DEPARTURE_DESTINATION_CALLBACK("EDIT_BEFORE_SAVE_SWAP_DEP_DEST"),
    EDIT_BEFORE_SAVE_DATE_CALLBACK("EDIT_BEFORE_SAVE_DATE"),
    EDIT_BEFORE_SAVE_CHANGE_DATE_CALLBACK("EDIT_BEFORE_SAVE_CHANGE_DATE:"),
    EDIT_BEFORE_SAVE_TIME_CALLBACK("EDIT_BEFORE_SAVE_TIME"),
    EDIT_BEFORE_SAVE_CHANGE_TIME_STATUS("EDIT_BEFORE_SAVE_CHANGE_TIME"),
    EDIT_BEFORE_SAVE_CAR_CALLBACK("EDIT_BEFORE_SAVE_CAR"),
    EDIT_BEFORE_SAVE_CHANGE_CAR_CALLBACK("EDIT_BEFORE_SAVE_CHANGE_CAR:"),
    EDIT_BEFORE_SAVE_SEATS_QUANTITY_CALLBACK("EDIT_BEFORE_SAVE_SEATS_QUANTITY"),
    EDIT_BEFORE_SAVE_CHANGE_SEATS_QUANTITY_STATUS("EDIT_BEFORE_SAVE_CHANGE_SEATS_QUANTITY_STATUS"),
    EDIT_BEFORE_SAVE_COMMENTARY_CALLBACK("EDIT_BEFORE_SAVE_COMMENTARY"),
    GET_ACTIVE_REQUESTS_LIST("GET_ACTIVE_REQUESTS_LIST"),
    EDIT_SETTLEMENT_LOCATION_CALLBACK("EDIT_SETTLEMENT_LOCATION:"),
    EDIT_DATE_TAME_CALLBACK("EDIT_DATE_TAME:"),
    EDIT_CAR_DETAILS_CALLBACK("EDIT_CAR_DETAILS:"),
    EDIT_COMMENTARY_CALLBACK("EDIT_COMMENTARY:"),
    EDIT_DEPARTURE_SETTLEMENT_CALLBACK("EDIT_BEFORE_SAVE_DEP_SETTLEMENT"),
    EDIT_CHANGE_DEPARTURE_SETTLEMENT_CALLBACK("EDIT_BEFORE_SAVE_CHANGE_DEP_SETTLEMENT:"),
    EDIT_DESTINATION_SETTLEMENT_CALLBACK("EDIT_BEFORE_SAVE_DEST_SETTLEMENT"),
    EDIT_CHANGE_DESTINATION_SETTLEMENT_CALLBACK("EDIT_BEFORE_SAVE_CHANGE_DEST_SETTLEMENT:"),
    EDIT_DEPARTURE_LOCATION_CALLBACK("EDIT_BEFORE_SAVE_DEP_LOCATION"),
    EDIT_CHANGE_DEPARTURE_LOCATION_CALLBACK("EDIT_BEFORE_SAVE_CHANGE_DEP_LOCATION:"),
    EDIT_DESTINATION_LOCATION_CALLBACK("EDIT_BEFORE_SAVE_DEST_LOCATION"),
    EDIT_CHANGE_DESTINATION_LOCATION_CALLBACK("EDIT_BEFORE_SAVE_CHANGE_DEST_LOCATION:"),
    EDIT_SWAP_DEPARTURE_DESTINATION_CALLBACK("EDIT_BEFORE_SAVE_SWAP_DEP_DEST"),
    ;

    private final String value;

    FindPassengerOperation(String value) {
        this.value = value;
    }
}
