package by.ivam.fellowtravelerbot.bot.enums;

import lombok.Getter;

@Getter
public enum UserOperation {
    START_REGISTRATION_CALLBACK("START_REGISTRATION_CALLBACK"),
    DENY_REGISTRATION_CALLBACK("DENY_REGISTRATION_CALLBACK"),
    REGISTRATION_EDIT_NAME("REGISTRATION_EDIT_NAME"),
    REGISTRATION_GET_EDITED_NAME_CHAT_STATUS("REGISTRATION_GET_EDITED_NAME_CHAT_STATUS"),
    REQUEST_SETTLEMENT_CALLBACK("REQUEST_SETTLEMENT_CALLBACK"),
    SAVE_SETTLEMENT_CALLBACK("SAVE_SETTLEMENT_CALLBACK:"),
    EDIT_NAME_CALLBACK("EDIT_NAME_CALLBACK"),
    EDIT_NAME_CHAT_STATUS("EDIT_NAME_CHAT_STATUS"),
    CHANGE_SETTLEMENT_REQUEST_CALLBACK("CHANGE_SETTLEMENT_REQUEST_CALLBACK"),
    CHANGE_SETTLEMENT_CALLBACK("CHANGE_SETTLEMENT_CALLBACK:"),
    DELETE_USER("DELETE_USER"),
    CONFIRM_USER_DELETION("CONFIRM_USER_DELETION");
    private final String value;

    UserOperation(String value) {
        this.value = value;
    }
}
