package by.ivam.fellowtravelerbot.bot.enums;

import lombok.Getter;

@Getter
public enum UserOperation {
    START_REGISTRATION_CALLBACK("START_REGISTRATION_CALLBACK"),
    DENY_REGISTRATION_CALLBACK("DENY_REGISTRATION_CALLBACK"),
    REGISTRATION_EDIT_NAME("REGISTRATION_EDIT_NAME"),
    REGISTRATION_GET_EDITED_NAME("REGISTRATION_GET_EDITED_NAME"),
    REQUEST_SETTLEMENT_CALLBACK("REQUEST_SETTLEMENT_CALLBACK"),
    SAVE_SETTLEMENT_CALLBACK("SAVE_SETTLEMENT_CALLBACK:"),
    ;
 private final String value;
    UserOperation(String value) {
        this.value=value;
    }
}
