package by.ivam.fellowtravelerbot.handler.enums;

import lombok.Getter;


@Getter
public enum ChatStatus {
    NO_STATUS,
    REGISTRATION_USER_EDIT_NAME,
    USER_EDIT_NAME,
    ADD_CAR_MODEL,
    ADD_CAR_COLOR,
    ADD_CAR_PLATES,
    ADD_CAR_COMMENTARY,
    ADD_CAR_EDIT_MODEL,
    ADD_CAR_EDIT_COLOR,
    ADD_CAR_EDIT_PLATES,
    ADD_CAR_EDIT_COMMENTARY,
    EDIT_FIRST_CAR_MODEL,
    EDIT_FIRST_CAR_COLOR,
    EDIT_FIRST_CAR_PLATES,
    EDIT_FIRST_CAR_COMMENTARY,
    EDIT_SECOND_CAR_MODEL,
    EDIT_SECOND_CAR_COLOR,
    EDIT_SECOND_CAR_PLATES,
    EDIT_SECOND_CAR_COMMENTARY
}
